# Sample.ipynb
This notebook showcases the basic functionality of the package.

## Preparation
Perform imports and create as sample covariance matrix.

In [1]:
import numpy as np

In [2]:
sigma_hat = np.diag((1,2,3))
print('Sample covariance matrix:')
print(sigma_hat)

Sample covariance matrix:
[[1 0 0]
 [0 2 0]
 [0 0 3]]


## Estimation methods

In [3]:
import covariance_DRO

In [4]:
print(covariance_DRO.estimate_cov.__doc__)


    Estimate Covariance matrix using distributionally robust optimization
    
    Parameters
    ----------
    sigma_hat : numpy.ndarray
        the sample covariance matrix
    epsilon : float
        the radius of the uncertainty ball 
    method : string
        the method to use. must be one of the following:
        'KLdirect', ...
    tol : float, optional
        stopping criterion for optimization
    maxit : float or int, optional
        maximum number of iterations for optimization
        
    Raises
    ------
    ValueError
        negative ball radius
    ValueError
        invalid method
    ValueError
        non-positive-semidefinite covariance matrix
        
    Returns
    -------
    sigma_star : numpy ndarray
        the estimated covariance matrix
    


### KLdirect method

In [5]:
# calculate covariance matrix with direct KL-method
sigma_star = covariance_DRO.estimate_cov(sigma_hat, 1e-2, 'KLdirect')

In [6]:
print('Sigma_star using KLdirect')
print(sigma_star)

Sigma_star using KLdirect
[[0.90080037 0.         0.        ]
 [0.         1.47096271 0.        ]
 [0.         0.         1.8050465 ]]


### More methods to be added soon...